export enum PERMISSIONS {
  SCHOOL = "school",
  SCHOOL_EDIT = "school-edit",
  SCHOOL_ACCEPT = "school-accept",
  PARTICIPANT = "participant",
  PARTICIPANT_EDIT = "participant-edit",
  TRANSACTION = "transaction",
  TRANSACTION_EDIT = "transaction-edit",
  REGION = "region",
  REGION_EDIT = "region-edit",
  SETTING = "setting",
  USER = "user",
  USER_EDIT = "user-edit",
  ADMIN = "admin",
  ADMIN_EDIT = "admin-edit",
}
