export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  REG_SEKOLAH: "/register/sekolah",
  USER: "/user",
  SEKOLAH: "/user/school",
  SCHOOL_EDIT: "/user/school/edit",
  SCHOOL_WAITING: "/user/school/waiting",
  SCHOOL_DETAIL: "/user/school/waiting/detail",
  PESERTA: "/user/peserta",
  PESERTA_EDIT: "/user/peserta/edit",
  TRANSACTION: "/user/transaction",
  RAYON: "/user/rayon",
  ADMIN: "/user/admin",
};
