export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  USER: "/user",
  SCHOOL: "/user/school",
  SCHOOL_EDIT: "/user/school/school-edit",
  SCHOOL_WAITING: "/user/school/waiting",
  PARTICIPANT: "/user/participant",
  PARTICIPANT_EDIT: "/user/participant/participant-edit",
  USERS: "/user/users",
  USERS_EDIT: "/user/users",
  TRANSACTION: "/user/transaction",
  REGION: "/user/region",
  SETTING: "/user/setting",
  ADMIN: "/user/admin",
  ADMIN_ROLE: "/user/admin/role",
};
